### ISSUE TITLE
SafeAndNullableExtensions.cs 有点问题

### ISSUE THREAD

**Issue by xingwen1987** [CosmosLoops/Cosmos#4]
`public static string SafeString(this object @object) => (@object as string).SafeValue();`
这个地方，如果传入 int t = 0; t.SafeString()，个人认为应该返回 “0”

**Comment by xingwen1987** [comment]
`public static string SafeString(this object @object) => (@object == null ? string.Empty : @object.ToString()).SafeValue();`
我改成了这样。

**Comment by xingwen1987** [comment]
`public static Guid? SafeGuid(this object @object) => @object as Guid?;`
我也改成了
`public static Guid? ToSafeGuid(this object @object)
        {
            return @object is string ? Guid.Parse(@object.ToSafeString()) : @object as Guid?;
        }`

**Comment by alexinea** [comment]
Safe系列主要是对Nullable的值的安全获得。也许你需要的是[这个](https://github.com/CosmosLoops/Cosmos/blob/dev/Standard/src/Cosmos.Extensions/ConversionExtensions.cs) 和 [这个](https://github.com/CosmosLoops/Cosmos/blob/dev/Standard/src/Cosmos/Conversions/ObjectConversion.cs) 。
